### ISSUE TITLE
how can i use the sticky component from 'dist'

### ISSUE THREAD

**Issue by Rockergmail** [airyland/vux#430] opened 2016-07-27 07:33 UTC
### Expected behavior and actual behavior.
####What i expected:
using the sticky component by 
```
var sticky = require('vux/dist/components/sticky/index.js')
```

####What i get:
when webpack, it comes out these:
```
ERROR in ./~/vux/dist/components/sticky/index.js
Module parse failed: /home/rocker/vhost/ad/wind-h5/node_modules/vux/dist/components/sticky/index.js 'import' and 'export' may only appear at the top level (140:1)
You may need an appropriate loader to handle this file type.
SyntaxError: 'import' and 'export' may only appear at the top level (140:1)
    at Parser.pp.raise (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.parseStatement (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:1759:29)
    at Parser.pp.parseBlock (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseFunctionBody (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:610:22)
    at Parser.pp.parseFunction (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:2089:8)
    at Parser.pp.parseExprAtom (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:321:19)
    at Parser.pp.parseExprSubscripts (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExprList (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:660:23)
    at Parser.pp.parseExprAtom (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:312:28)
    at Parser.pp.parseExprSubscripts (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExprList (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:660:23)
    at Parser.pp.parseSubscripts (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:252:29)
    at Parser.pp.parseExprSubscripts (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:231:15)
    at Parser.pp.parseMaybeUnary (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseReturnStatement (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:1872:26)
    at Parser.pp.parseStatement (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:1737:19)
    at Parser.pp.parseBlock (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseFunctionBody (/home/rocker/vhost/ad/wind-h5/node_modules/webpack/node_modules/acorn/dist/acorn.js:610:22)
 @ ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app/components/App.vue 11:13-56
```
### Steps to reproduce the problem
just write the code in the vue file
```
var sticky = require('vux/dist/components/sticky/index.js')
```

================UPDATA=================
I compare my vux/dist/components/sticky/index.js and the one on github, it is different after i run the command `node build/build-components `

and the vux/dist/components/sticky/index.js i got is:
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["vuxSticky"] = factory();
	else
		root["vuxSticky"] = factory();
})(this, function() {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;
/******/
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	module.exports = __webpack_require__(4);


/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	'use strict';
	
	Object.defineProperty(exports, "__esModule", {
	  value: true
	});
	
	var _sticky = __webpack_require__(5);
	
	var _sticky2 = _interopRequireDefault(_sticky);
	
	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
	
	exports.default = {
	  ready: function ready() {
	    (0, _sticky2.default)(this.$el);
	  }
	};

/***/ },
/* 2 */
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = " <div><slot></slot></div> ";

/***/ },
/* 4 */
/***/ function(module, exports, __webpack_require__) {

	var __vue_script__, __vue_template__
	__webpack_require__(2)
	__vue_script__ = __webpack_require__(1)
	__vue_template__ = __webpack_require__(3)
	module.exports = __vue_script__ || {}
	if (module.exports.__esModule) module.exports = module.exports.default
	if (__vue_template__) {
	(typeof module.exports === "function" ? (module.exports.options || (module.exports.options = {})) : module.exports).template = __vue_template__
	}


/***/ },
/* 5 */
/***/ function(module, exports) {

	// http://efe.baidu.com/blog/position-sticky/
	
	// 检测iOS版本大于等于6
	function gtIOS6 () {
	  var userAgent = window.navigator.userAgent
	  var ios = userAgent.match(/(iPad|iPhone|iPod)\s+OS\s([\d_\.]+)/)
	  return ios && ios[2] && (parseInt(ios[2].replace(/_/g, '.'), 10) >= 6)
	}
	
	// 判断是否支持sticky属性
	function isSupportSticky () {
	  var prefixTestList = ['', '-webkit-', '-ms-', '-moz-', '-o-']
	  var stickyText = ''
	  for (var i = 0; i < prefixTestList.length; i++) {
	    stickyText += 'position:' + prefixTestList[i] + 'sticky'
	  }
	  // 创建一个dom来检查
	  var div = document.createElement('div')
	  var body = document.body
	  div.style.cssText = 'display:none' + stickyText
	  body.appendChild(div)
	  var isSupport = /sticky/i.test(window.getComputedStyle(div).position)
	  body.removeChild(div)
	  div = null
	  return isSupport
	}
	
	export default function (nav) {
	  if (gtIOS6() || isSupportSticky()) {
	    // 大于等于iOS6版本使用sticky
	    nav.classList.add('vux-sticky')
	  } else {
	    var navOffsetY = nav.offsetTop
	    window.addEventListener('scroll', function () {
	      window.scrollY >= navOffsetY ? nav.classList.add('vux-fixed') : nav.classList.remove('vux-fixed')
	    })
	  }
	}


/***/ }
/******/ ])
});
;
```

**Comment by airyland** [comment] 2016-07-27 08:03
strange thing.. you required sticky but why came out progress error..

**Comment by Rockergmail** [comment] 2016-07-27 08:37
@airyland ...Oppps..my mistaken copy,  and I have updated

**Comment by Rockergmail** [comment] 2016-08-02 07:25
@airyland  any ideas? i can require('vux/dist/components/sticky/index.js') in Window, but Ubuntu can't.

**Comment by airyland** [comment] 2016-08-02 07:51
Could you provide your .babalrc content and webpack version?

**Comment by Rockergmail** [comment] 2016-08-02 08:48
@airyland 
Version: webpack 1.13.1
babel: {
        presets: ['es2015'],
        plugins: ['transform-runtime']
    },

**Comment by airyland** [comment] 2016-08-11 21:22
The issue is closed as it cannot be reproduced. Try the latest version and try to import components from `src`(it's a better way since you are using webpack). And could you tell me what made you so angry https://github.com/Rockergmail/vux/commit/afb67e6921b636c9e5738ab46c8ebe57ff475875

**Closed by airyland** 2016-08-11 21:22 UTC

**Comment by Rockergmail** [comment] 2016-08-12 06:04
For basic component like flexbox or input stuff, I just import there styles in need. The major reason is too big when i webpack, so i just give up the way from src.

**Comment by Rockergmail** [comment] 2016-08-12 06:36
@airyland ...无语..作者真的不好意思，我真的不是在攻击作者和该项目，这是我一些无厘头的commit坏习惯，i fuck = fix。。越说越奇怪。。
